Add website BAPC 2020
WISVCH/chipcie-legacy pull request #1
Opened 2023-03-27 05:59 UTC by verwoerd

2023-03-28 19:27 UTC, mpsijm requested changes

2023-03-28 19:27 UTC, mpsijm commented on README.md
> +BAPC 2020 uses JavaScipt-based routing and can't be scraped. The files are copied directly from the old image, built from https://github.com/WISVCH/bapc2020.
Curse this JavaScript-based routing :sweat_smile:

We still need to fix the dynamic 404 page redirect to `index.html`, in a similar way as was done in https://github.com/WISVCH/bapc2020/pull/10/files. We can apply the exact same fix, but I _only_ want to do this for 2020.bapc.eu (and not for the other domains). Some googling for conditional `try_files` got me nothing except explanations as to why you should not have conditional `try_files` in Nginx. I guess we could duplicate the entire config to make this single exception for 2020.bapc.eu, but that also feels ugly :upside_down_face: Do you have any ideas?

2023-03-28 19:37 UTC, verwoerd commented on README.md
> +BAPC 2020 uses JavaScipt-based routing and can't be scraped. The files are copied directly from the old image, built from https://github.com/WISVCH/bapc2020.
how bad would it be if all 404 redirect to `index.html` for all pages?

2023-03-28 19:56 UTC, mpsijm commented on README.md
> +BAPC 2020 uses JavaScipt-based routing and can't be scraped. The files are copied directly from the old image, built from https://github.com/WISVCH/bapc2020.
Assuming that all other archived websites use only valid URLs, it should be fine. It's just that the original versions of these websites did not have this redirect-all-404 configuration, as it should™ be :stuck_out_tongue: 

I found a different solution and implemented it in ddea3ea01ec90b49888efb9a40d2448fb2e94ff8. It's kinda ugly, but it works :stuck_out_tongue: Let me know if you agree :slightly_smiling_face:

2023-03-29 03:32 UTC, verwoerd commented on README.md
> +BAPC 2020 uses JavaScipt-based routing and can't be scraped. The files are copied directly from the old image, built from https://github.com/WISVCH/bapc2020.
lgtm

2023-03-29 07:11 UTC, mpsijm commented on README.md
> +BAPC 2020 uses JavaScipt-based routing and can't be scraped. The files are copied directly from the old image, built from https://github.com/WISVCH/bapc2020.
Yep, that makes sense, because the fix doesn't redirect everything back to index.html, but only the selected routes. Good enough for me, they're still 404 pages :slightly_smiling_face:

2023-03-29 07:11 UTC, mpsijm approved these changes

2023-03-29 07:14 UTC, merged